services:
  postgres-local:
    container_name: postgres-local
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: postgres:14.17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: